eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true