server:
  port: 8889

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 86400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    password: ${AUTH_DB_PASSWORD}
    url: jdbc:mysql://db:3306/authdb
    username: ${AUTH_DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

facebook:
  identifier-prefix: ${FACEBOOK_USERNAME_PREFIX}
  default-password: ${FACEBOOK_DEFAULT_PASSWORD}

test-data:
  user-email: ${TEST_USER_USERNAME}
  user-password: ${TEST_USER_PASSWORD}
  moderator-email: ${TEST_MODERATOR_USERNAME}
  moderator-password: ${TEST_MODERATOR_PASSWORD}
  admin-email: ${TEST_ADMIN_USERNAME}
  admin-password: ${TEST_ADMIN_PASSWORD}
  fb-user-identifier: ${TEST_FB_USER_USERNAME}
  fb-user-password: ${FACEBOOK_DEFAULT_PASSWORD}