server:
  port: 4000

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: asku-auth-service
          uri: lb://asku-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: asku-account-service
          uri: lb://asku-account-service
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
            - RemoveRequestHeader=Authorization
            - UserParamFilter
        - id: asku-magazine-service
          uri: lb://asku-magazine-service
          predicates:
            - Path=/magazine/**
          filters:
            - RewritePath=/magazine/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
            - RemoveRequestHeader=Authorization
            - UserParamFilter