server:
  port: 4000

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: asku-auth-service
          uri: lb://asku-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: asku-magazine-service
          uri: lb://asku-magazine-service
          predicates:
            - Path=/magazine/**
          filters:
            - RewritePath=/magazine/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
        - id: asku-image-service
          uri: http://asku-image-service:8892
          predicates:
            - Path=/image/**
          filters:
            - RewritePath=/image/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie