server:
  port: 4000

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: asku-auth-service
          uri: lb://asku-auth-service
          predicates:
            - Path=/auth/**
            - RewritePath=^/auth,
        - id: asku-account-service
          uri: lb://asku-account-service
          predicates:
            - Path=/account/**
            - RewritePath=^/account,